export const EVALUATE_APPLICATION_REQUEST = "EVALUATE_APPLICATION_REQUEST";
export const EVALUATE_APPLICATION_REQUEST_SUCCESS = "EVALUATE_APPLICATION_REQUEST_SUCCESS";
export const EVALUATE_APPLICATION_REQUEST_FAIL = "EVALUATE_APPLICATION_REQUEST_FAIL";
export const EVALUATE_APPLICATION_REQUEST_RESET = "EVALUATE_APPLICATION_REQUEST_RESET";

export const ADD_BLACKLIST_REQUEST = "ADD_BLACKLIST_REQUEST";
export const ADD_BLACKLIST_REQUEST_SUCCESS = "ADD_BLACKLIST_REQUEST_SUCCESS";
export const ADD_BLACKLIST_REQUEST_FAIL = "ADD_BLACKLIST_REQUEST_FAIL";
export const ADD_BLACKLIST_REQUEST_RESET = "ADD_BLACKLIST_REQUEST_RESET";

export const ADD_JOB_REQUEST = "ADD_JOB_REQUEST";
export const ADD_JOB_REQUEST_SUCCESS = "ADD_JOB_REQUEST_SUCCESS";
export const ADD_JOB_REQUEST_FAIL = "ADD_JOB_REQUEST_FAIL";
export const ADD_JOB_REQUEST_RESET = "ADD_JOB_REQUEST_RESET";

export const SEARCH_APPLICANT_REQUEST = "SEARCH_APPLICANT_REQUEST";
export const SEARCH_APPLICANT_SUCCESS = "SEARCH_APPLICANT_SUCCESS";
export const SEARCH_APPLICANT_FAIL = "SEARCH_APPLICANT_FAIL";
export const SEARCH_APPLICANT_RESET = "SEARCH_APPLICANT_RESET";

export const CLOSE_JOB_REQUEST = "CLOSE_JOB_REQUEST";
export const CLOSE_JOB_SUCCESS = "CLOSE_JOB_SUCCESS";
export const CLOSE_JOB_FAIL = "CLOSE_JOB_FAIL";
export const CLOSE_JOB_RESET = "CLOSE_JOB_RESET";

export const CHANGE_JOB_STATUS_REQUEST = "CHANGE_JOB_STATUS_REQUEST";
export const CHANGE_JOB_STATUS_SUCCESS = "CHANGE_JOB_STATUS_SUCCESS";
export const CHANGE_JOB_STATUS_FAIL = "CHANGE_JOB_STATUS_FAIL";
export const CHANGE_JOB_STATUS_RESET = "CHANGE_JOB_STATUS_RESET";