export const APPLICATION_LOAD_REQUEST = "APPLICATION_LOAD_REQUEST";
export const APPLICATION_LOAD_SUCCESS = "APPLICATION_LOAD_SUCCESS";
export const APPLICATION_LOAD_FAIL = "APPLICATION_LOAD_FAIL";
export const APPLICATION_LOAD_RESET = "APPLICATION_LOAD_RESET";

export const LOAD_APPLICANT_APPLICATION_REQUEST = "LOAD_APPLICANT_APPLICATION_REQUEST";
export const LOAD_APPLICANT_APPLICATION_SUCCESS = "LOAD_APPLICANT_APPLICATION_SUCCESS";
export const LOAD_APPLICANT_APPLICATION_FAIL = "LOAD_APPLICANT_APPLICATION_FAIL";
export const LOAD_APPLICANT_APPLICATION_RESET = "LOAD_APPLICANT_APPLICATION_RESET";